### PR TITLE
Fix feature tests on M1 MacBooks

### PR DESCRIPTION
**Pull request by wilson1000-MoJ**
## Description
Locally, feature tests are failing on M1 MacBooks, this is true for both Docker and direct-host-machine installations. 

This work fixes the feature tests and explores ways to improve the development environment for all that work on CTS.

## Self-review checklist

* [ ] (1) Quick stakeholder demo done OR
* [ ] (2) ...bug with before and after screenshots
* [ ] (3) Tests passing
* [ ] (4) Branch ready to be merged (not work in progress)
* [ ] (5) No superfluous changes in diff
* [ ] (6) No TODO's without new ticket numbers
* [ ] (7) PR Prefixed with ticket number e.g. `CT-7654 ...`
* [ ] (8) Data migration script is created if any of letter templates is changed

### CODE REVIEW

**Comment by vertism** [comment]
@wilson1000-MoJ I'm on an M1 mac and my tests work locally (apart from some which require an S3 bucket)

**Comment by wilson1000-MoJ** [comment]
Good feedback, thanks, Andrew.

**Comment by wilson1000-MoJ** [comment]
May I ask, did you use the ARM version of Chrome to get them working locally?

**Comment by vertism** [comment]
> May I ask, did you use the ARM version of Chrome to get them working locally?

Yes

**Comment by vertism** [comment]
Closing as it's quite out of date, and I'm not sure it's relevant anymore.

**Pull request closed without merging**
