### PR TITLE
CT-2444 Refactor offender sars factory

### PR DESCRIPTION
**Pull request by mseedat-moj**
## Description
Reduces complexity in Offender SAR factory by deleting unused values and replacing factories with traits as per existing convention. Refactors affected cases. This work is to allow tests for #895 to pass. Failing tests in this PR (translation file alleged missing keys) are unrelated to this ticket.
 
## Self-review checklist

* [X] (1) Quick stakeholder demo done OR
* [X] (2) ...bug with before and after screenshots
* [X] (3) Tests passing
* [X] (4) Branch ready to be merged (not work in progress)
* [X] (5) No superfluous changes in diff
* [X] (6) No TODO's without new ticket numbers
 
##### factories/cases/offender_sars.rb before
Screen Shot 2019-08-28 at 16 33 05

##### factories/cases/offender_sars.rb after
Screen Shot 2019-08-28 at 16 34 49

### Related JIRA tickets
https://dsdmoj.atlassian.net/browse/CT-2444
 
### Deployment
N/A
 
### Manual testing instructions
N/A

### CODE REVIEW

**Comment by mseedat-moj** [comment]
Build failure is due to the issue of the translation tests believing translation keys are missing. This is an error due to the parent branch #896 and unrelated to changes in this branch. Recommend merge @danielatdigital

**Comment by Polsonby** [comment]
Thanks for picking up on this, Mo  :)

**Review by danielatdigital — APPROVED** [review]

**Review by Polsonby — APPROVED** [review]
Great work 👍 thanks for tidying up :)

**Comment by mseedat-moj** [comment]
Superceded by Parent PR:

https://github.com/ministryofjustice/correspondence_tool_staff/pull/900

**Pull request closed without merging**
