### PR TITLE
CT-2581 Add K8s settings to Master (interim)

### PR DESCRIPTION
**Pull request by mseedat-moj**
## Description
Forgot to switch the branch base to master prior to PR merge #94
 
## Self-review checklist

* [X] (1) Quick stakeholder demo done OR
* [X] (2) ...bug with before and after screenshots
* [X] (3) Tests passing
* [X] (4) Branch ready to be merged (not work in progress)
* [X] (5) No superfluous changes in diff
* [X] (6) No TODO's without new ticket numbers

### CODE REVIEW

**Comment by Polsonby** [comment]
Sorry, I should have checked when reviewing...

**Comment by Polsonby** [comment]
Gah! Why put the close button beside the Comment button ?!!!!!

**Comment by mseedat-moj** [comment]
> Gah! Why put the close button beside the Comment button ?!!!!!

I completely forgot to flip the base branch. What a div

**Comment by mseedat-moj** [comment]
Resolved conflicts directly against master

**Pull request closed without merging**
