### PR TITLE
CT-362 add sidekiq

### PR DESCRIPTION
**Pull request by misaka**
https://dsdmoj.atlassian.net/browse/CT-362

This adds an ActiveJob for our mail process using SideKiq and Redis. Basically, so that we can email out notifications to our users.

This work will be require changes in the deploy repo to make it to the deployed environments.

### CODE REVIEW

**Comment by EdwardAndress** [comment]
Why is an empty job and, corresponding, empty spec added here?

**Comment by misaka** [comment]
Because I wanted to have some kind of job in here, even if it gets renamed later, etc. I was assuming that we would require _a_ job to be able to spin up SideKiq.

**Comment by EdwardAndress** [comment]
Can you test that?

**Comment by EdwardAndress** [comment]
I approve either way

**Comment by EdwardAndress** [comment]
Although given that ActiveJob is also compatible with other queueing systems, it would be possible to switch out Sidekiq for something else at some point in the future.  This would be made easier if adding sidekiq were separated from adding the jobs, at least in terms of the commits used.

**Comment by misaka** [comment]
@EdwardAndress I didn't think it was worth proving, tbh. I don't think there's enough benefit to be had, even if we do decide to rip out SideKiq I don't think we'd do a revert commit, I think we'd just add the gem and edit the config files.

**Comment by EdwardAndress** [comment]
OK

**Comment by misaka** [comment]
@aliuk2012 @EdwardAndress Sorry for more changes coming through, but there was some things that needed fixing. If you could re-review I'd appreciate it. :)

**Pull request merged**
