### PR TITLE
CDPT-128 offender sar removed fromsubject details from offender sar complaints…

### PR DESCRIPTION
**Pull request by rohanssalunkhe**
… page

## Self-review checklist

* [ ] (1) Quick stakeholder demo done OR
* [ ] (2) ...bug with before and after screenshots
* [ ] (3) Tests passing
* [ ] (4) Branch ready to be merged (not work in progress)
* [ ] (5) No superfluous changes in diff
* [ ] (6) No TODO's without new ticket numbers
* [ ] (7) PR Prefixed with ticket number e.g. `CT-7654 ...`
* [ ] (8) Data migration script is created if any of letter templates is changed

### CODE REVIEW

**Review by Polsonby — APPROVED** [review]
LGTM :)

**Comment by Polsonby** [comment]
It's a bit worrying that no specs failed after removing this 🤔

**Comment by rohanssalunkhe** [comment]
> It's a bit worrying that no specs failed after removing this 🤔

Because there are no feature specs for offender sar

**Review by Polsonby — CHANGES_REQUESTED** [review]
Edit: sorry - never mind, I got confused. User error!

**Review by Polsonby — APPROVED** [review]

**Pull request merged**
